# Render.com deployment configuration for split frontend/backend
version: "1"

services:
  # Backend API service
  - type: web
    name: rehearsal-scheduler-backend
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend static site service
  - type: web
    name: rehearsal-scheduler-frontend
    buildCommand: npm install && npm run build
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: "https://rehearsal-scheduler-backend.onrender.com/api"
      - key: EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
        sync: false
