# Render.com deployment configuration
version: "1"

services:
  # Web service for the API
  - type: web
    name: rehearsal-scheduler-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CACHE_VERSION
        value: "v2.0"

databases:
  # PostgreSQL database
  - name: rehearsal-scheduler-db
    plan: free
