# Render.com deployment configuration
version: "1"

services:
  # Web service for the API
  - type: web
    name: rehearsal-scheduler-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: CACHE_VERSION
        value: "v2.0"
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: "https://rehearsal-scheduler.onrender.com/api/calendar/auth/google/callback"

# Note: Using external MongoDB Atlas, no Render database needed
# databases:
#   - name: rehearsal-scheduler-db
#     plan: free
